<?php

namespace App\Services;

// Default
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

// Packages
use Monolog\Logger;
use Monolog\Handler\StreamHandler;
use Carbon\Carbon;

// Controllers
use App\Http\Controllers\gatewayController;

class externalFunctions
{
    // Get Token
    public static function getToken() {

        // Call external API with Basic Auth to get the token
        $response = Http::withBasicAuth(config('botinfo.username'), config('botinfo.password'))
                    ->get(config('botinfo.externalUrl') . '/api/v2/tokens/api/ownerId/' . config('botinfo.botId'));
        if($response->getStatusCode() < 300) {
            // Return the token if the request was successful
            config(['botinfo.externalToken' => $response->json()['data']['token']]);
            config(['botinfo.externalTokenExpiry' => $response->json()['data']['expiresAtMillis']]);

            return $response->json()['data']['token'];
        } else {
            // Log the error if the request failed
            $msg = [
                'error' => 'Failed to get token from external',
                'status' => $response->status(),
                'response' => $response->body()
            ];
            self::log($msg, 'externalErrors.log');
            return false;
        }
    }

    // Hands off
    public static function handsOff($json) {
        // check if now timestamp is less than token expiry timestamp (1739871509128)
        $token = config('botinfo.externalTokenExpiry') > Carbon::now()->timestamp * 1000 ? config('botinfo.externalToken') : self::getToken();
        if(!$token) {
            return false;
        }
        $response = Http::withHeaders([
            'Authorization' => 'Bearer ' . $token,
        ])->put(config('botinfo.externalUrl') . '/bots/v3/control', $json);
        if($response->status() < 300) {
            return $response;
        } else {
            // Log the error if the request failed
            $msg = [
                'error' => 'Failed to hand off to agent',
                'status' => $response->status(),
                'response' => $response->body()
            ];
            self::log($msg, 'externalErrors.log');
            return false;
        }
        
    }

    // Change Workqueue
    public static function changeWorkqueue($json) {
        // check if now timestamp is less than token expiry timestamp (1739871509128)
        $token = config('botinfo.externalTokenExpiry') > Carbon::now()->timestamp * 1000 ? config('botinfo.externalToken') : self::getToken();
        if(!$token) {
            return false;
        }

        // Set the workqueue based on the type
        $response = Http::withHeaders([
                'Authorization' => 'Bearer ' . $token,
            ])
            ->put(config('botinfo.externalUrl') . '/bots/v3/workqueue', $json);
        if($response->status() < 300) {
            return $response;
        } else {
            // Log the error if the request failed
            $msg = [
                'error' => 'Failed to change workqueue',
                'status' => $response->status(),
                'response' => $response->body()
            ];
            self::log($msg, 'externalErrors.log');
            return false;
        }
    }

    // log
    public static function log($message, $file) {
        $endLog = new Logger("messages");
        
        // File name
        $endLog->pushHandler(new StreamHandler(storage_path("logs/{$file}")), Logger::INFO);
        
        // Items to be logged
        $endLogMsg = [$message];
        $endLog->info('Logs Generated by externalFunctions', $endLogMsg);

        return "Logged successfully";
    }
}